title: Mini Numbers
description: Privacy-first, self-hosted web analytics
remote_theme: just-the-docs/just-the-docs@v0.10.1

url: "https://onemanstudiodotse.github.io"
baseurl: "/mini-numbers"

color_scheme: light

aux_links:
  "GitHub":
    - "https://github.com/OneManStudioDotSe/mini-numbers"

nav_enabled: true
search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Mini Numbers is open source under the <a href=\"https://github.com/OneManStudioDotSe/mini-numbers/blob/main/LICENSE\">MIT License</a>."

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red
